-- CREATING DATABASE
CREATE DATABASE IF NOT EXISTS temp;

-- DISPLAY DATABSES
SHOW DATABASES;

-- USING DATABASE
USE temp;

-- CREATING TABLE
CREATE TABLE student (
id INT PRIMARY KEY,
name VARCHAR(255)
);

-- DISPLAY TABLE
SHOW TABLES;

-- RENAME COLUMN
ALTER TABLE student CHANGE COLUMN id student_id INT PRIMARY KEY;