-- CREATING DATABASE
CREATE DATABASE IF NOT EXISTS temp;

-- DISPLAY DATABSES
SHOW DATABASES;

-- USING DATABASE
USE temp;

-- CREATING TABLE
CREATE TABLE student (
id INT PRIMARY KEY,
name VARCHAR(255)
);

-- DISPLAY TABLE
SHOW TABLES;

-- INSERTING INTO TABLE
INSERT INTO student VALUES(1, 'ronit');

-- SELECT 
SELECT * FROM student;

-- DELETING DATABASE
DROP DATABASE ronitdb;